/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package standard_file_manager;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author James Josue Molina
 */
public class Enlazado extends javax.swing.JFrame {

    /**
     * Creates new form Enlazado
     */
    public Enlazado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Estructura de Datos II");
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/icono.png"));
        this.setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_Archivo1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_Archivo2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Archivo3 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("➜");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jl_Archivo1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_Archivo1);

        jScrollPane2.setViewportView(jl_Archivo2);

        jButton2.setText("Archivo 1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Archivo 2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jl_Archivo3.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_Archivo3);

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reiniciar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton1)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            JFileChooser path = new JFileChooser();
            path.showOpenDialog(this);
            archivo1 = new Archivo(new File(path.getSelectedFile().getPath()));
            jl_Archivo1.setModel(new DefaultListModel());
            DefaultListModel model = (DefaultListModel)jl_Archivo1.getModel();
            for (int i = 0; i < archivo1.getCampos().size(); i++) {
                model.addElement(archivo1.getCampos().get(i));
            }
        }catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            JFileChooser path = new JFileChooser();
            path.showOpenDialog(this);
            archivo2 = new Archivo(new File(path.getSelectedFile().getPath()));
            jl_Archivo2.setModel(new DefaultListModel());
            DefaultListModel model = (DefaultListModel)jl_Archivo2.getModel();
            for (int i = 0; i < archivo2.getCampos().size(); i++) {
                
                model.addElement(archivo2.getCampos().get(i));
            }
            
        }catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Enlazado E = new Enlazado();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            boolean Si1 = true, Si2 = true;
            DefaultListModel modelo = (DefaultListModel)jl_Archivo1.getModel();
            DefaultListModel modelo2 = (DefaultListModel)jl_Archivo2.getModel();
            DefaultListModel modelo3 = (DefaultListModel)jl_Archivo3.getModel();
            try{
                if(jl_Archivo1.getSelectedIndex() >= 0){
                    for (int i = 0; i < modelo3.getSize(); i++) {
                        if( modelo3.getElementAt(i) == modelo.getElementAt(jl_Archivo1.getSelectedIndex()) ){
                            Si1 = false;
                        }    
                    }
                    if( Si1 ){
                        modelo3.addElement(modelo.getElementAt(jl_Archivo1.getSelectedIndex()));
                    }
            }
            }catch(Exception e){
                
            }
            try{
                if(jl_Archivo2.getSelectedIndex() >= 0){
                    for (int i = 0; i < modelo3.getSize(); i++) {
                        if( modelo3.getElementAt(i) == modelo2.getElementAt(jl_Archivo2.getSelectedIndex()) ){
                            Si2 = false;
                        }    
                    }
                    if( Si2 ){
                        modelo3.addElement(modelo2.getElementAt(jl_Archivo2.getSelectedIndex()));
                    }
                }
            }catch(Exception e){
                
            }
            jl_Archivo3.setModel(modelo3);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            DefaultListModel modelo3 = (DefaultListModel)jl_Archivo3.getModel();
            ArrayList<Campo> campos = new ArrayList();
            for (int i = 0; i < modelo3.size(); i++) {
                campos.add((Campo)modelo3.getElementAt(i));
            }
            JFileChooser path = new JFileChooser();
            path.showOpenDialog(this);
            //Uni_archivo2 = new Archivo(new File("prueba.txt") );
            archivo3.setCampos(campos);
            if (!archivo3.getCampos().isEmpty()) {
                String metaData = "";//registros = ""
                int recordSize = 0;//recNum = 0;
                for (int i = 0; i < archivo3.getCampos().size(); i++) {
                    if (i == 0) {
                        metaData += '{';
                        }
                        metaData += archivo3.getCampos().get(i).toString();
                        if (i == archivo3.getCampos().size() - 1) {
                            metaData += '}';
                    } else {
                        metaData += ", ";
                    }
                    recordSize += archivo3.getCampos().get(i).getSize()+1;
                }
                metaData += "\n" + Integer.toString(recordSize);
                metaData += "\n" + archivo3.getContRegis()+"\n";

                try {
                    System.out.println(path.getSelectedFile().getPath());
                    fw = new FileWriter(path.getSelectedFile().getPath()+".txt");
                    bw = new BufferedWriter(fw);
                    bw.append(metaData);
                    for (int i = 0; i < archivo3.getRegistros().size(); i++) {
                        bw.append(archivo3.getRegistros().get(i).toString()+ "\n");
                    }
                    bw.flush();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(this, "Se ha salvado correctamente");
                } catch (IOException ex) {
                    System.out.println("ME MAME PERRIN");
                }

                if(!archivo3.getRegistros().isEmpty()){
                    bt.escribirArchivo();
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enlazado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enlazado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enlazado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enlazado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enlazado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jl_Archivo1;
    private javax.swing.JList<String> jl_Archivo2;
    private javax.swing.JList<String> jl_Archivo3;
    // End of variables declaration//GEN-END:variables
    int campoSelec;
    Archivo Uni_archivo1 = new Archivo();
    Archivo Uni_archivo2 = new Archivo();
    Archivo archivo = new Archivo();
    Archivo archivo1 = new Archivo();
    Archivo archivo2 = new Archivo();
    Archivo archivo3 = new Archivo();
    BufferedWriter bw;
    FileWriter fw;
    AdminBTree bt;
    //ArrayList<Registro> RegistroTemp = new ArrayList();
    int IDTemp = 0;
    Archivo ArchivoPerson = new Archivo();
    Archivo ArchivoCity = new Archivo();
}
