/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package standard_file_manager;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author James Josue Molina
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_menuArchivos = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        btn_Nuevo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jb_abrirArchivo = new javax.swing.JButton();
        jf_menuCampos = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jb_crearCampo = new javax.swing.JButton();
        jb_listarCampos = new javax.swing.JButton();
        jb_modificarCampo = new javax.swing.JButton();
        jb_borrarCampo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listaCampos = new javax.swing.JTable();
        jb_borrarCampo6 = new javax.swing.JButton();
        jd_crearCampo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_tipoCampo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_sizeCampo = new javax.swing.JTextField();
        jb_crearCampoDialog = new javax.swing.JButton();
        jd_modificarCampo = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreModCampo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_tipoModCampo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tf_sizeModCampo = new javax.swing.JTextField();
        jb_modCampoDialog = new javax.swing.JButton();
        jf_menuRegistros = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jb_crearCampo1 = new javax.swing.JButton();
        jb_listarCampos1 = new javax.swing.JButton();
        jb_modificarRegistro = new javax.swing.JButton();
        jb_borrarCampo1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_listaCampos1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jb_borrarCampo2 = new javax.swing.JButton();
        jb_borrarCampo3 = new javax.swing.JButton();
        jb_borrarCampo4 = new javax.swing.JButton();
        jb_borrarCampo5 = new javax.swing.JButton();
        cb_registros = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jb_menuCampos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Menú de Archivos");

        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jb_abrirArchivo.setText("Abrir");
        jb_abrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_abrirArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_menuArchivosLayout = new javax.swing.GroupLayout(jf_menuArchivos.getContentPane());
        jf_menuArchivos.getContentPane().setLayout(jf_menuArchivosLayout);
        jf_menuArchivosLayout.setHorizontalGroup(
            jf_menuArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_menuArchivosLayout.createSequentialGroup()
                .addGroup(jf_menuArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_menuArchivosLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1))
                    .addGroup(jf_menuArchivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jf_menuArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jf_menuArchivosLayout.createSequentialGroup()
                                .addComponent(btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton2))
                            .addGroup(jf_menuArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_Salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Cerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jf_menuArchivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Salvar))
                    .addGroup(jf_menuArchivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_abrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jf_menuArchivosLayout.setVerticalGroup(
            jf_menuArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_menuArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jf_menuArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Nuevo)
                    .addComponent(jButton2))
                .addGap(38, 38, 38)
                .addComponent(jb_abrirArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_Salvar)
                .addGap(32, 32, 32)
                .addComponent(btn_Cerrar)
                .addGap(29, 29, 29)
                .addComponent(btn_Salir)
                .addGap(46, 46, 46))
        );

        jLabel2.setText("Menú campos");

        jb_crearCampo.setText("Crear campo");
        jb_crearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCampoMouseClicked(evt);
            }
        });

        jb_listarCampos.setText("Listar campos");
        jb_listarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarCamposMouseClicked(evt);
            }
        });

        jb_modificarCampo.setText("Modificar campo");
        jb_modificarCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarCampoMouseClicked(evt);
            }
        });
        jb_modificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarCampoActionPerformed(evt);
            }
        });

        jb_borrarCampo.setText("Eliminar campo");
        jb_borrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarCampoActionPerformed(evt);
            }
        });

        jt_listaCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Tamaño"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_listaCampos);

        jb_borrarCampo6.setText("Volver");
        jb_borrarCampo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarCampo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_menuCamposLayout = new javax.swing.GroupLayout(jf_menuCampos.getContentPane());
        jf_menuCampos.getContentPane().setLayout(jf_menuCamposLayout);
        jf_menuCamposLayout.setHorizontalGroup(
            jf_menuCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_menuCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(174, 174, 174))
            .addGroup(jf_menuCamposLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jf_menuCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_modificarCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_listarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crearCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarCampo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jf_menuCamposLayout.setVerticalGroup(
            jf_menuCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_menuCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jf_menuCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_menuCamposLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jb_crearCampo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_listarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(jb_modificarCampo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_borrarCampo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_borrarCampo6))
                    .addGroup(jf_menuCamposLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Crear campo");

        jLabel4.setText("Nombre del campo");

        cb_tipoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entero", "Caracter" }));

        jLabel5.setText("Tipo de dato");

        jLabel6.setText("Tamaño del campo");

        jb_crearCampoDialog.setText("Crear campo");
        jb_crearCampoDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCampoDialogMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearCampoLayout = new javax.swing.GroupLayout(jd_crearCampo.getContentPane());
        jd_crearCampo.getContentPane().setLayout(jd_crearCampoLayout);
        jd_crearCampoLayout.setHorizontalGroup(
            jd_crearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCampoLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jd_crearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreCampo)
                    .addComponent(cb_tipoCampo, 0, 209, Short.MAX_VALUE)
                    .addComponent(tf_sizeCampo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearCampoLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jd_crearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearCampoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearCampoLayout.createSequentialGroup()
                        .addComponent(jb_crearCampoDialog)
                        .addGap(147, 147, 147))))
        );
        jd_crearCampoLayout.setVerticalGroup(
            jd_crearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_sizeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_crearCampoDialog)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel7.setText("Modificar campo");

        jLabel8.setText("Nombre del campo");

        jLabel9.setText("Tipo de dato");

        cb_tipoModCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entero", "Caracter" }));

        jLabel10.setText("Tamaño del campo");

        jb_modCampoDialog.setText("Modificar campo");
        jb_modCampoDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modCampoDialogMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarCampoLayout = new javax.swing.GroupLayout(jd_modificarCampo.getContentPane());
        jd_modificarCampo.getContentPane().setLayout(jd_modificarCampoLayout);
        jd_modificarCampoLayout.setHorizontalGroup(
            jd_modificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarCampoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(149, 149, 149))
            .addGroup(jd_modificarCampoLayout.createSequentialGroup()
                .addGroup(jd_modificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarCampoLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jd_modificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(tf_nombreModCampo)
                            .addComponent(cb_tipoModCampo, 0, 167, Short.MAX_VALUE)
                            .addComponent(tf_sizeModCampo)))
                    .addGroup(jd_modificarCampoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jb_modCampoDialog)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jd_modificarCampoLayout.setVerticalGroup(
            jd_modificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombreModCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_tipoModCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_sizeModCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_modCampoDialog)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel11.setText("MENU REGISTROS");

        jb_crearCampo1.setText("Cargar Registros");
        jb_crearCampo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCampo1MouseClicked(evt);
            }
        });

        jb_listarCampos1.setText("Introducir Registro");
        jb_listarCampos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarCampos1MouseClicked(evt);
            }
        });
        jb_listarCampos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listarCampos1ActionPerformed(evt);
            }
        });

        jb_modificarRegistro.setText("Modificar Registro");
        jb_modificarRegistro.setEnabled(false);
        jb_modificarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarRegistroMouseClicked(evt);
            }
        });

        jb_borrarCampo1.setText("Buscar Registro");
        jb_borrarCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarCampo1ActionPerformed(evt);
            }
        });

        jt_listaCampos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_listaCampos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_listaCampos1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_listaCampos1);

        jList1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jList1);

        jb_borrarCampo2.setText("Borrar Registro");
        jb_borrarCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarCampo2ActionPerformed(evt);
            }
        });

        jb_borrarCampo3.setText("Listar Registro");
        jb_borrarCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarCampo3ActionPerformed(evt);
            }
        });

        jb_borrarCampo4.setText("Cruzar Archivo");
        jb_borrarCampo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarCampo4ActionPerformed(evt);
            }
        });

        jb_borrarCampo5.setText("Volver");
        jb_borrarCampo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarCampo5ActionPerformed(evt);
            }
        });

        cb_registros.setEnabled(false);

        javax.swing.GroupLayout jf_menuRegistrosLayout = new javax.swing.GroupLayout(jf_menuRegistros.getContentPane());
        jf_menuRegistros.getContentPane().setLayout(jf_menuRegistrosLayout);
        jf_menuRegistrosLayout.setHorizontalGroup(
            jf_menuRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_menuRegistrosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jf_menuRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_modificarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_listarCampos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crearCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarCampo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarCampo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarCampo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarCampo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_registros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jf_menuRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_menuRegistrosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(jf_menuRegistrosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jf_menuRegistrosLayout.setVerticalGroup(
            jf_menuRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_menuRegistrosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jf_menuRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jf_menuRegistrosLayout.createSequentialGroup()
                        .addComponent(jb_crearCampo1)
                        .addGap(18, 18, 18)
                        .addComponent(jb_listarCampos1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_borrarCampo1)
                        .addGap(18, 18, 18)
                        .addComponent(jb_borrarCampo2)
                        .addGap(18, 18, 18)
                        .addComponent(jb_borrarCampo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_borrarCampo4)
                        .addGap(18, 18, 18)
                        .addComponent(jb_borrarCampo5)
                        .addGap(18, 18, 18)
                        .addComponent(jb_modificarRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Archivos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jb_menuCampos.setText("Campos");
        jb_menuCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_menuCamposMouseClicked(evt);
            }
        });

        jButton3.setText("Registro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jb_menuCampos)
                    .addComponent(jButton1))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jb_menuCampos)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        JFileChooser path = new JFileChooser();
        path.showOpenDialog(this);
        //File file;
        System.out.println(path.getSelectedFile().getPath().substring(path.getSelectedFile().getPath().length() - 4, path.getSelectedFile().getPath().length()));
        if (path.getSelectedFile().getPath().substring(path.getSelectedFile().getPath().length() - 4, path.getSelectedFile().getPath().length()).equals(".txt")) {
            Uni_archivo = new File(path.getSelectedFile().getPath());
            archivo.setArchivo(Uni_archivo);
        } else {
            Uni_archivo = new File(path.getSelectedFile().getPath() + ".txt");
            archivo.setArchivo(Uni_archivo);
        }
        if (!Uni_archivo.exists()) {
            try {
                Uni_archivo.createNewFile();
                archivo.setArchivo(Uni_archivo);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_NuevoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        jf_menuArchivos.pack();
        jf_menuArchivos.setVisible(true);
        jf_menuArchivos.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_crearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCampoMouseClicked
        jd_crearCampo.setVisible(true);
        jd_crearCampo.pack();
        jd_crearCampo.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_crearCampoMouseClicked

    private void jb_menuCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_menuCamposMouseClicked
        this.setVisible(false);
        jf_menuCampos.pack();
        jf_menuCampos.setVisible(true);
        jf_menuCampos.setLocationRelativeTo(this);

    }//GEN-LAST:event_jb_menuCamposMouseClicked

    private void jb_crearCampoDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCampoDialogMouseClicked
        String nombre = tf_nombreCampo.getText();
        boolean isChar;
        if (((String) cb_tipoCampo.getSelectedItem()).equals("Entero")) {
            isChar = false;
        } else {
            isChar = true;
        }
        int size = Integer.parseInt(tf_sizeCampo.getText());

        Campo campo = new Campo(nombre, isChar, size);
        camposTemp.add(campo);

        tf_nombreCampo.setText("");
        tf_sizeCampo.setText("");
        cb_tipoCampo.setSelectedIndex(0);
    }//GEN-LAST:event_jb_crearCampoDialogMouseClicked

    private void jb_listarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarCamposMouseClicked
        actualizarTablaCampos();
    }//GEN-LAST:event_jb_listarCamposMouseClicked

    private void jb_modificarCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarCampoMouseClicked
        if (campoSeleccionado() != -1) {
            Campo c = camposTemp.get(campoSeleccionado());
            tf_nombreModCampo.setText(c.getNombre());
            if (c.isIsChar()) {
                cb_tipoModCampo.setSelectedIndex(1);
            } else {
                cb_tipoModCampo.setSelectedIndex(0);
            }
            tf_sizeModCampo.setText(Integer.toString(c.getSize()));
            jd_modificarCampo.pack();
            jd_modificarCampo.setVisible(true);
            jd_modificarCampo.setLocationRelativeTo(this);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un campo para poder modificarlo");
        }
    }//GEN-LAST:event_jb_modificarCampoMouseClicked

    private void jb_modCampoDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modCampoDialogMouseClicked
        String nombre = tf_nombreModCampo.getText();
        boolean isChar;
        if (((String) cb_tipoModCampo.getSelectedItem()).equals("Entero")) {
            isChar = false;
        } else {
            isChar = true;
        }
        int size = Integer.parseInt(tf_sizeModCampo.getText());

        Campo campo = new Campo(nombre, isChar, size);
        camposTemp.get(campoSelec).setNombre(nombre);
        camposTemp.get(campoSelec).setIsChar(isChar);
        camposTemp.get(campoSelec).setSize(size);

        tf_nombreModCampo.setText("");
        tf_sizeModCampo.setText("");
        cb_tipoModCampo.setSelectedIndex(0);
    }//GEN-LAST:event_jb_modCampoDialogMouseClicked

    private void jb_borrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarCampoActionPerformed
        int aux = jt_listaCampos.getSelectedRow();
        if (aux >= 0) {
            camposTemp.remove(aux);
            actualizarTablaCampos();
        }

    }//GEN-LAST:event_jb_borrarCampoActionPerformed

    private void jb_modificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_modificarCampoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed

        if (!camposTemp.isEmpty()) {
            String metaData = "", registros = "";
            int recordSize = 0, recNum = 0;
            for (int i = 0; i < camposTemp.size(); i++) {
                if (i == 0) {
                    metaData += '{';
                }
                metaData += camposTemp.get(i).toString();
                if (i == camposTemp.size() - 1) {
                    metaData += '}';
                } else {
                    metaData += ", ";
                }
                recordSize += camposTemp.get(i).getSize() + 1;
            }
            metaData += "\n" + Integer.toString(recordSize);
            metaData += "\n" + recNum;
      
            try {
                fw = new FileWriter(Uni_archivo);
                bw = new BufferedWriter(fw);
                bw.append(metaData);
                bw.flush();
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(this, "Se ha salvado correctamente");
            } catch (IOException ex) {
                System.out.println("ME MAME PERRIN");
            }

        } else {
            jf_menuCampos.pack();
            jf_menuCampos.setVisible(true);
            jf_menuCampos.setLocationRelativeTo(this);
        }

        //jf_menuArchivos.setVisible(false);
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
            System.out.println("ME MAME PERRO x2");
        }
        JOptionPane.showMessageDialog(this, "Se ha cerrado el archivo");
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void jb_crearCampo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCampo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_crearCampo1MouseClicked

    private void jb_listarCampos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarCampos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_listarCampos1MouseClicked

    private void jb_modificarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarRegistroMouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_registros.getModel();
        int pos = modelo.getIndexOf(modelo.getSelectedItem());
        Registro temp = RegistroTemp.get(jt_listaCampos1.getSelectedRow());
        String aux = JOptionPane.showInputDialog(null, "Ingrese el campo (" + camposTemp.get(pos).toString() + ")");
        if( !(aux == null) ){
            if (camposTemp.get(pos).isIsChar()) {
                if (aux.length() <= camposTemp.get(pos).getSize()) {
                    temp.getPablo().set(pos,aux);
                } else {
                    while (!(aux.length() <= camposTemp.get(pos).getSize())) {
                        aux = JOptionPane.showInputDialog(null, "Ingrese el campo nuevamente (" + camposTemp.get(pos).toString() + ")");
                    }
                   temp.getPablo().set(pos,aux);
                }
            } else {
                if (aux.length() <= camposTemp.get(pos).getSize() && calcIsNumeric(aux)) {
                    temp.getPablo().set(pos,aux);
                } else {
                    while (!(aux.length() <= camposTemp.get(pos).getSize() && calcIsNumeric(aux))) {
                        aux = JOptionPane.showInputDialog(null, "Ingrese el campo nuevamente (" + camposTemp.get(pos).toString() + ")");
                    }
                    temp.getPablo().set(pos,aux);
                }
            }
        }
        cb_registros.setEnabled(false);
        jb_modificarRegistro.setEnabled(false);
    }//GEN-LAST:event_jb_modificarRegistroMouseClicked

    private void jb_borrarCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_borrarCampo1ActionPerformed

    private void jb_borrarCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_borrarCampo2ActionPerformed

    private void jb_borrarCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarCampo3ActionPerformed
        jt_listaCampos1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        DefaultTableModel modeloListaCampo = (DefaultTableModel) jt_listaCampos1.getModel();
        for (int i = 0; i < RegistroTemp.size(); i++) {
            Object[] id = {RegistroTemp.get(i).getID()};
            modeloListaCampo.addRow(id);
        }
        jt_listaCampos1.setModel(modeloListaCampo);
    }//GEN-LAST:event_jb_borrarCampo3ActionPerformed

    private void jb_borrarCampo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarCampo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_borrarCampo4ActionPerformed

    private void jb_borrarCampo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarCampo5ActionPerformed
        this.setVisible(true);
        jf_menuRegistros.pack();
        jf_menuRegistros.setVisible(false);
    }//GEN-LAST:event_jb_borrarCampo5ActionPerformed

    private void jb_listarCampos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listarCampos1ActionPerformed
        Registro temp = new Registro();
        for (int i = 0; i < camposTemp.size(); i++) {
            String aux = JOptionPane.showInputDialog(null, "Ingrese el campo (" + camposTemp.get(i).toString() + ")");
            if (camposTemp.get(i).isIsChar()) {
                if (aux.length() <= camposTemp.get(i).getSize()) {
                    temp.Agregar(aux);
                } else {
                    while (!(aux.length() <= camposTemp.get(i).getSize())) {
                        aux = JOptionPane.showInputDialog(null, "Ingrese el campo nuevamente (" + camposTemp.get(i).toString() + ")");
                    }
                    temp.Agregar(aux);
                }
            } else {
                if (aux.length() <= camposTemp.get(i).getSize() && calcIsNumeric(aux)) {
                    temp.Agregar(aux);
                } else {
                    while (!(aux.length() <= camposTemp.get(i).getSize() && calcIsNumeric(aux))) {
                        aux = JOptionPane.showInputDialog(null, "Ingrese el campo nuevamente (" + camposTemp.get(i).toString() + ")");
                    }
                    temp.Agregar(aux);
                }
            }//btn_Salir
        }
        temp.setID("MMCJ" + (IDTemp++));
        RegistroTemp.add(temp);
    }//GEN-LAST:event_jb_listarCampos1ActionPerformed

    private void jb_borrarCampo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarCampo6ActionPerformed
        this.setVisible(true);
        jf_menuCampos.pack();
        jf_menuCampos.setVisible(false);
    }//GEN-LAST:event_jb_borrarCampo6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(true);
        jf_menuArchivos.pack();
        jf_menuArchivos.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        jf_menuRegistros.pack();
        jf_menuRegistros.setVisible(true);
        jf_menuRegistros.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jt_listaCampos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_listaCampos1MouseClicked
        jList1.setModel(new DefaultListModel());
        cb_registros.setModel(new DefaultComboBoxModel());
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        DefaultComboBoxModel cbModel = (DefaultComboBoxModel) cb_registros.getModel();
        Registro temp = RegistroTemp.get(jt_listaCampos1.getSelectedRow());
        for (int i = 0; i < temp.getPablo().size(); i++) {
            model.addElement(camposTemp.get(i).getNombre() + ": " + temp.getPablo().get(i));
            cbModel.addElement(camposTemp.get(i).getNombre());
        }
        jList1.setModel(model);
        cb_registros.setEnabled(true);
        jb_modificarRegistro.setEnabled(true);
    }//GEN-LAST:event_jt_listaCampos1MouseClicked

    private void jb_abrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_abrirArchivoMouseClicked
        JFileChooser path = new JFileChooser();
        path.showOpenDialog(this);
        //File file;
        if (path.getSelectedFile().getPath().substring(path.getSelectedFile().getPath().length() - 4, path.getSelectedFile().getPath().length()).equals(".txt")) {
            System.out.println(path.getSelectedFile().getPath());
            Uni_archivo = new File(path.getSelectedFile().getPath());
            try {
                archivo = new Archivo(Uni_archivo);
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
        } /*else {
            Uni_archivo = new File(path.getSelectedFile().getPath() + ".txt");
            try {
                archivo = new Archivo(Uni_archivo);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_jb_abrirArchivoMouseClicked

    public static boolean calcIsNumeric(String x) {
        boolean isNumeric = true;
        try {
            Integer.parseInt(x);
        } catch (Exception e) {
            isNumeric = false;
        }
        return isNumeric;
    }

    private int campoSeleccionado() {
        int campoSeleccionado = -1;
        DefaultTableModel modelo = (DefaultTableModel) jt_listaCampos.getModel();
        if (jt_listaCampos.getSelectedRow() >= -1) {
            campoSeleccionado = jt_listaCampos.getSelectedRow();
            System.out.println(campoSeleccionado);
        }
        campoSelec = campoSeleccionado;
        return campoSeleccionado;
    }

    private void actualizarTablaCampos() {
        jt_listaCampos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Tipo", "Tamaño"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        DefaultTableModel modelo = (DefaultTableModel) jt_listaCampos.getModel();
        for (Campo c : camposTemp) {
            Object[] info = {c.getNombre(), c.getIsChar(), c.getSize()};
            modelo.addRow(info);
        }
        jt_listaCampos.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JComboBox<String> cb_registros;
    private javax.swing.JComboBox<String> cb_tipoCampo;
    private javax.swing.JComboBox<String> cb_tipoModCampo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_abrirArchivo;
    private javax.swing.JButton jb_borrarCampo;
    private javax.swing.JButton jb_borrarCampo1;
    private javax.swing.JButton jb_borrarCampo2;
    private javax.swing.JButton jb_borrarCampo3;
    private javax.swing.JButton jb_borrarCampo4;
    private javax.swing.JButton jb_borrarCampo5;
    private javax.swing.JButton jb_borrarCampo6;
    private javax.swing.JButton jb_crearCampo;
    private javax.swing.JButton jb_crearCampo1;
    private javax.swing.JButton jb_crearCampoDialog;
    private javax.swing.JButton jb_listarCampos;
    private javax.swing.JButton jb_listarCampos1;
    private javax.swing.JButton jb_menuCampos;
    private javax.swing.JButton jb_modCampoDialog;
    private javax.swing.JButton jb_modificarCampo;
    private javax.swing.JButton jb_modificarRegistro;
    private javax.swing.JDialog jd_crearCampo;
    private javax.swing.JDialog jd_modificarCampo;
    private javax.swing.JFrame jf_menuArchivos;
    private javax.swing.JFrame jf_menuCampos;
    private javax.swing.JFrame jf_menuRegistros;
    private javax.swing.JTable jt_listaCampos;
    private javax.swing.JTable jt_listaCampos1;
    private javax.swing.JTextField tf_nombreCampo;
    private javax.swing.JTextField tf_nombreModCampo;
    private javax.swing.JTextField tf_sizeCampo;
    private javax.swing.JTextField tf_sizeModCampo;
    // End of variables declaration//GEN-END:variables
    ArrayList<Campo> camposTemp = new ArrayList();
    int campoSelec;
    File Uni_archivo;
    Archivo archivo = new Archivo();
    BufferedWriter bw;
    FileWriter fw;
    ArrayList<Registro> RegistroTemp = new ArrayList();
    int IDTemp = 0;
}
